### ISSUE TITLE
camera preview is not show

### ISSUE THREAD

**Issue by liugang1014** [farice/ARShooter#1]
i run you code on iphone6 with ios11 beta,but camera preview is not show,why?

**Comment by farice** [comment]
This is because ARWorldTrackingSessionConfiguration is only supported on iOS devices with an A9 processor or later.

> On other devices supported by ARKit, the 
ARSessionConfiguration base class provides basic motion tracking that permits slightly less immersive AR experiences.

Hence, you can replace `ARWorldTrackingSessionConfiguration()` in ViewController.swift with `ARSessionConfiguration()` to run the demo (and comment out plane detection). However, as noted above, it will be a "slightly less immersive" experience.

**My recent commit https://github.com/farice/ARShooter/commit/ff81fe01d0e3e470b64f1f6fbfe1ac5397250fe5  should take care of this automatically for you.**

Let me know. @liugang1014

**Comment by liugang1014** [comment]
@farice ,i changed device from iphone6plus to iphone 6s plus,then i got the camera  preview.
thank you all the same.

**Comment by farice** [comment]
You're welcome! @liugang1014
